#!/bin/bash

roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_AHG_Library_Fri_Nov_5_21.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Bass_Rec_Fri_Nov_26_126.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Butler_Foodtruck_Fri_Nov_26_132.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Fountain_Library_Mon_Nov_8_26.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_AHG_Library_Wed_Nov_10_46.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_EER_AHG_Mon_Nov_8_32.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Library_AHG_Tue_Nov_9_43.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Library_Dobie_Wed_Nov_10_57.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Parlin_Parlin_Wed_Nov_10_51.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Stadium_Rec_Fri_Nov_26_135.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_LBJ_Stadium_Sat_Nov_13_105.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_GDC_Jester_Thu_Nov_18_121.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/train_bags/A_Spot_Stadium_PerformingArtsCenter_Sat_Nov_13_106.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/val_bags/A_Spot_AHG_GDC_Tue_Nov_9_41.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/val_bags/A_Spot_Butler_LBJ_Sat_Nov_13_104.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/val_bags/A_Spot_Library_Fountain_Tue_Nov_9_35.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data/val_bags/A_Spot_UTTower_Union_Wed_Nov_10_61.bag"