#!/bin/bash

roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_AHG_Library_Fri_Nov_5_21.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_LBJ_Stadium_Sat_Nov_13_105.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Stadium_PerformingArtsCenter_Sat_Nov_13_106.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Ahg_Library_Wed_Nov_10_56.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Library_Dobie_Wed_Nov_10_57.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Union_Union_Wed_Nov_10_67.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Bass_Rec_Fri_Nov_26_126.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Library_Fountain_Mon_Nov_8_30.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Welch_Union_Thu_Nov_11_71.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Bass_Rec_Fri_Nov_26_128.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Library_Fountain_Tue_Nov_9_35.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/B_Spot_AHG_Library_Tue_Nov_9_34.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Dobie_Fountain_Fri_Nov_12_84.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_SAC_GeorgeWashStatue_Wed_Nov_10_50.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/B_Spot_LBJ_Thompson_Sat_Nov_13_101.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Fountain_Library_Fri_Nov_12_85.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/A_Spot_Security_NHB_Wed_Nov_10_54.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/train_bags/B_Spot_Thompson_Thompson_Sat_Nov_13_100.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/val_bags/A_Spot_Butler_LBJ_Sat_Nov_13_104.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/val_bags/A_Spot_Fountain_Dobie_Fri_Nov_12_83.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/val_bags/A_Spot_Library_MLK_Thu_Nov_18_123.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/val_bags/A_Spot_Dobie_Littlefield_Wed_Nov_10_58.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/val_bags/A_Spot_Library_AHG_Thu_Nov_4_22.bag"
roslaunch parser.launch rosbag_path:="/catkin_ws/data2/val_bags/B_Spot_Dobie_Library_Thu_Nov_11_74.bag"